# Generated by Django 5.0.1 on 2024-02-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20240217_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A user with that phone already exists.'}, max_length=50, unique=True),
        ),
    ]
